package com.cbwleft.sms.dao.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`t_app`")
public class App {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.id
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
	@Id
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.name
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.private_key
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.prefix
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.validate_code_length
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private Byte validateCodeLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.channel_params
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private String channelParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_app.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.id
     *
     * @return the value of t_app.id
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.id
     *
     * @param id the value for t_app.id
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.name
     *
     * @return the value of t_app.name
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.name
     *
     * @param name the value for t_app.name
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.private_key
     *
     * @return the value of t_app.private_key
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.private_key
     *
     * @param privateKey the value for t_app.private_key
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.prefix
     *
     * @return the value of t_app.prefix
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.prefix
     *
     * @param prefix the value for t_app.prefix
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.validate_code_length
     *
     * @return the value of t_app.validate_code_length
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public Byte getValidateCodeLength() {
        return validateCodeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.validate_code_length
     *
     * @param validateCodeLength the value for t_app.validate_code_length
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setValidateCodeLength(Byte validateCodeLength) {
        this.validateCodeLength = validateCodeLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.channel_params
     *
     * @return the value of t_app.channel_params
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public String getChannelParams() {
        return channelParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.channel_params
     *
     * @param channelParams the value for t_app.channel_params
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setChannelParams(String channelParams) {
        this.channelParams = channelParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.create_date
     *
     * @return the value of t_app.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.create_date
     *
     * @param createDate the value for t_app.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_app.update_date
     *
     * @return the value of t_app.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_app.update_date
     *
     * @param updateDate the value for t_app.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", privateKey=").append(privateKey);
        sb.append(", prefix=").append(prefix);
        sb.append(", validateCodeLength=").append(validateCodeLength);
        sb.append(", channelParams=").append(channelParams);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        App other = (App) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPrivateKey() == null ? other.getPrivateKey() == null : this.getPrivateKey().equals(other.getPrivateKey()))
            && (this.getPrefix() == null ? other.getPrefix() == null : this.getPrefix().equals(other.getPrefix()))
            && (this.getValidateCodeLength() == null ? other.getValidateCodeLength() == null : this.getValidateCodeLength().equals(other.getValidateCodeLength()))
            && (this.getChannelParams() == null ? other.getChannelParams() == null : this.getChannelParams().equals(other.getChannelParams()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_app
     *
     * @mbg.generated Wed Apr 25 23:49:58 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPrivateKey() == null) ? 0 : getPrivateKey().hashCode());
        result = prime * result + ((getPrefix() == null) ? 0 : getPrefix().hashCode());
        result = prime * result + ((getValidateCodeLength() == null) ? 0 : getValidateCodeLength().hashCode());
        result = prime * result + ((getChannelParams() == null) ? 0 : getChannelParams().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}