package com.cbwleft.sms.dao.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`t_message`")
public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
	@Id
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.mobile
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.params
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.validate_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String validateCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.template_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Short templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.send_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Byte sendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.validate_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Byte validateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.fail_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String failCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.biz_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String bizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.recive_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Date reciveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.mobile
     *
     * @return the value of t_message.mobile
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.mobile
     *
     * @param mobile the value for t_message.mobile
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.params
     *
     * @return the value of t_message.params
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.params
     *
     * @param params the value for t_message.params
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.validate_code
     *
     * @return the value of t_message.validate_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getValidateCode() {
        return validateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.validate_code
     *
     * @param validateCode the value for t_message.validate_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setValidateCode(String validateCode) {
        this.validateCode = validateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.template_id
     *
     * @return the value of t_message.template_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Short getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.template_id
     *
     * @param templateId the value for t_message.template_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setTemplateId(Short templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.send_status
     *
     * @return the value of t_message.send_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Byte getSendStatus() {
        return sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.send_status
     *
     * @param sendStatus the value for t_message.send_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setSendStatus(Byte sendStatus) {
        this.sendStatus = sendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.validate_status
     *
     * @return the value of t_message.validate_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Byte getValidateStatus() {
        return validateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.validate_status
     *
     * @param validateStatus the value for t_message.validate_status
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setValidateStatus(Byte validateStatus) {
        this.validateStatus = validateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.fail_code
     *
     * @return the value of t_message.fail_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getFailCode() {
        return failCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.fail_code
     *
     * @param failCode the value for t_message.fail_code
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setFailCode(String failCode) {
        this.failCode = failCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.biz_id
     *
     * @return the value of t_message.biz_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.biz_id
     *
     * @param bizId the value for t_message.biz_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.recive_date
     *
     * @return the value of t_message.recive_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Date getReciveDate() {
        return reciveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.recive_date
     *
     * @param reciveDate the value for t_message.recive_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setReciveDate(Date reciveDate) {
        this.reciveDate = reciveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.create_date
     *
     * @return the value of t_message.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.create_date
     *
     * @param createDate the value for t_message.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.update_date
     *
     * @return the value of t_message.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.update_date
     *
     * @param updateDate the value for t_message.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mobile=").append(mobile);
        sb.append(", params=").append(params);
        sb.append(", validateCode=").append(validateCode);
        sb.append(", templateId=").append(templateId);
        sb.append(", sendStatus=").append(sendStatus);
        sb.append(", validateStatus=").append(validateStatus);
        sb.append(", failCode=").append(failCode);
        sb.append(", bizId=").append(bizId);
        sb.append(", reciveDate=").append(reciveDate);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Message other = (Message) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getParams() == null ? other.getParams() == null : this.getParams().equals(other.getParams()))
            && (this.getValidateCode() == null ? other.getValidateCode() == null : this.getValidateCode().equals(other.getValidateCode()))
            && (this.getTemplateId() == null ? other.getTemplateId() == null : this.getTemplateId().equals(other.getTemplateId()))
            && (this.getSendStatus() == null ? other.getSendStatus() == null : this.getSendStatus().equals(other.getSendStatus()))
            && (this.getValidateStatus() == null ? other.getValidateStatus() == null : this.getValidateStatus().equals(other.getValidateStatus()))
            && (this.getFailCode() == null ? other.getFailCode() == null : this.getFailCode().equals(other.getFailCode()))
            && (this.getBizId() == null ? other.getBizId() == null : this.getBizId().equals(other.getBizId()))
            && (this.getReciveDate() == null ? other.getReciveDate() == null : this.getReciveDate().equals(other.getReciveDate()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getParams() == null) ? 0 : getParams().hashCode());
        result = prime * result + ((getValidateCode() == null) ? 0 : getValidateCode().hashCode());
        result = prime * result + ((getTemplateId() == null) ? 0 : getTemplateId().hashCode());
        result = prime * result + ((getSendStatus() == null) ? 0 : getSendStatus().hashCode());
        result = prime * result + ((getValidateStatus() == null) ? 0 : getValidateStatus().hashCode());
        result = prime * result + ((getFailCode() == null) ? 0 : getFailCode().hashCode());
        result = prime * result + ((getBizId() == null) ? 0 : getBizId().hashCode());
        result = prime * result + ((getReciveDate() == null) ? 0 : getReciveDate().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}