package com.cbwleft.sms.dao.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`t_template`")
public class Template {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
	@Id
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.channel_template_no
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String channelTemplateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.name
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.type
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.validate_code_key
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private String validateCodeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.validate_code_expire
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Short validateCodeExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.app_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Byte appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.id
     *
     * @return the value of t_template.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.id
     *
     * @param id the value for t_template.id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.channel_template_no
     *
     * @return the value of t_template.channel_template_no
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getChannelTemplateNo() {
        return channelTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.channel_template_no
     *
     * @param channelTemplateNo the value for t_template.channel_template_no
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setChannelTemplateNo(String channelTemplateNo) {
        this.channelTemplateNo = channelTemplateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.name
     *
     * @return the value of t_template.name
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.name
     *
     * @param name the value for t_template.name
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.type
     *
     * @return the value of t_template.type
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.type
     *
     * @param type the value for t_template.type
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.template
     *
     * @return the value of t_template.template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.template
     *
     * @param template the value for t_template.template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.validate_code_key
     *
     * @return the value of t_template.validate_code_key
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public String getValidateCodeKey() {
        return validateCodeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.validate_code_key
     *
     * @param validateCodeKey the value for t_template.validate_code_key
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setValidateCodeKey(String validateCodeKey) {
        this.validateCodeKey = validateCodeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.validate_code_expire
     *
     * @return the value of t_template.validate_code_expire
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Short getValidateCodeExpire() {
        return validateCodeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.validate_code_expire
     *
     * @param validateCodeExpire the value for t_template.validate_code_expire
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setValidateCodeExpire(Short validateCodeExpire) {
        this.validateCodeExpire = validateCodeExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.app_id
     *
     * @return the value of t_template.app_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Byte getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.app_id
     *
     * @param appId the value for t_template.app_id
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setAppId(Byte appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.create_date
     *
     * @return the value of t_template.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.create_date
     *
     * @param createDate the value for t_template.create_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template.update_date
     *
     * @return the value of t_template.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template.update_date
     *
     * @param updateDate the value for t_template.update_date
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", channelTemplateNo=").append(channelTemplateNo);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", template=").append(template);
        sb.append(", validateCodeKey=").append(validateCodeKey);
        sb.append(", validateCodeExpire=").append(validateCodeExpire);
        sb.append(", appId=").append(appId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Template other = (Template) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getChannelTemplateNo() == null ? other.getChannelTemplateNo() == null : this.getChannelTemplateNo().equals(other.getChannelTemplateNo()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getTemplate() == null ? other.getTemplate() == null : this.getTemplate().equals(other.getTemplate()))
            && (this.getValidateCodeKey() == null ? other.getValidateCodeKey() == null : this.getValidateCodeKey().equals(other.getValidateCodeKey()))
            && (this.getValidateCodeExpire() == null ? other.getValidateCodeExpire() == null : this.getValidateCodeExpire().equals(other.getValidateCodeExpire()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template
     *
     * @mbg.generated Wed Apr 25 23:49:59 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getChannelTemplateNo() == null) ? 0 : getChannelTemplateNo().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getTemplate() == null) ? 0 : getTemplate().hashCode());
        result = prime * result + ((getValidateCodeKey() == null) ? 0 : getValidateCodeKey().hashCode());
        result = prime * result + ((getValidateCodeExpire() == null) ? 0 : getValidateCodeExpire().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}